// Spicy compliments for Jeopardy's "Komplimente-Modus". Positive, funny,
// a bit cheeky/flirty and body-confident — but playful, never crude. Shown to
// whoever just answered correctly; they accept it to keep playing.

export const SPICY_COMPLIMENTS = [
  'Richtig — und dabei siehst du auch noch zum Anbeißen aus. Unfair.',
  'Köpfchen UND Knackarsch? Das Universum hat bei dir übertrieben.',
  'So klug, dass es fast so heiß ist wie du selbst.',
  'Deine Antwort war richtig. Dein Lächeln ist strafbar.',
  'Brain, Beauty und Body — du Show-off.',
  'Wenn Schlausein sexy ist, bist du gerade Vollzeit-Model.',
  'Korrekt! Und ja, das Outfit sitzt heute verdammt gut.',
  'Du löst Fragen schneller, als du Herzen brichst — Respekt.',
  'Richtig. Hör auf, so attraktiv zu sein, wir wollen uns konzentrieren.',
  'Genie im Kopf, Sünde im Körper.',
  'Deine Augen lenken hier alle ab — die Antwort stimmt trotzdem.',
  'So heiß und auch noch richtig? Mach mal halblang.',
  'Diese Antwort + dieser Hintern = Gesamtpaket.',
  'Du bist der lebende Beweis, dass schlau das neue sexy ist.',
  'Richtig. Und nein, du darfst trotzdem nicht so gut aussehen.',
  'Charmant, clever, knackig — du hast beim Erschaffen gecheatet.',
  'Dein Grips ist genauso scharf wie dein Kieferknochen.',
  'Hätte nicht gedacht, dass jemand beim Nachdenken so gut aussieht. Doch.',
  'Korrekt! Und dein Selbstbewusstsein steht dir verdammt gut.',
  'Wenn du weiter so glänzt, brauchen wir alle Sonnenbrillen.',
  'So smart — kein Wunder, dass hier alle heimlich nach dir schielen.',
  'Richtige Antwort, unfaire Ausstrahlung.',
  'Du machst sogar Grübel-Falten sexy.',
  'Schultern wie ein Türrahmen, Hirn wie ein Lexikon. Stark.',
  'Diese Beine laufen direkt in die nächste Runde — richtig übrigens.',
  'Du bist ein glatter 10er, der auch noch die Antwort weiß.',
  'Heiß, schlagfertig und jetzt auch noch Punkte — ganz schön frech.',
  'Dein Lächeln allein wäre schon die volle Punktzahl wert.',
  'Korrekt. Und dieser Blick gerade? In drei Bundesländern verboten.',
  'Klug, witzig, zum Reinbeißen. Wer hat dich eigentlich programmiert?',
  'Richtig! Und ehrlich — dein Glow ist heute echt illegal.',
  'Du denkst scharf und siehst noch schärfer aus.',
  'Sexy UND ein Gewinnertyp. Manche haben einfach alles.',
  'Diese Antwort sitzt — so wie die Hose heute sitzt.',
  'Du bist der Grund, warum man sich beim Quiz nicht konzentrieren kann.',
  'Goldrichtig — und dein Body ist auch nicht von schlechten Eltern.',
  'So eine Mischung aus süß und heiß sollte eigentlich verboten sein.',
  'Richtig. Dein Selbstbewusstsein? Geradezu aphrodisierend.',
  'Kopf wie ein Profi, Ausstrahlung wie ein Rockstar.',
  'Punkt für dich — und ein heimliches Kompliment an deine Lippen.',
  'Du beantwortest Fragen und brichst nebenbei Herzen. Multitasking-Gott.',
  'Diese Hände wissen die Antwort UND sehen verdammt gut aus.',
  'Klug genug zum Gewinnen, heiß genug zum Anstarren.',
  'Richtig! Und ja, alle haben kurz hingeschaut, als du das gesagt hast.',
  'Du bist scharf wie deine Antwort — und die war messerscharf.',
  'Beim Anblick deiner Antwort (und von dir) ist uns kurz warm geworden.',
  'Schön, schlau, schlagfertig — drei von drei, du Angeber.',
  'Dein Hirn macht uns an und dein Grinsen erledigt den Rest.',
];

export function pickCompliment() {
  return SPICY_COMPLIMENTS[Math.floor(Math.random() * SPICY_COMPLIMENTS.length)];
}
