// Fragenkatalog für das "5 Schnelle Fragen"-Modul (Gemischtes Hack Style).
// Kurze, eindeutige "Lieber X oder Y?" / "Was wäre dir lieber"-Fragen.
// Nicht-kompetitiv: alle Teilnehmer sehen die gleiche Frage und diskutieren.
// Reihenfolge wird beim Start gemischt.
export const SCHNELLE_FRAGEN = [
  'Pommes oder Chips?',
  'Bergurlaub oder Strandurlaub?',
  'Hund oder Katze?',
  'Pizza oder Pasta?',
  'Frühaufsteher oder Nachteule?',
  'Bier oder Wein?',
  'Kaffee oder Tee?',
  'Stadt oder Land?',
  'Sommer oder Winter?',
  'Buch oder Film?',
  'Süß oder Salzig?',
  'Im Lotto gewinnen oder berühmt werden?',
  'Tausend kleine Probleme oder ein riesengroßes?',
  'Lieber 1 Stunde länger schlafen oder 1 Stunde später Feierabend?',
  'Lieber Hellsehen können oder Gedanken lesen?',
  'Lieber fliegen oder unsichtbar sein können?',
  'Lieber nie wieder Musik hören oder nie wieder Filme schauen?',
  'Lieber 5 Geschwister oder Einzelkind?',
  'Lieber nackt durch die Fußgängerzone oder vor versammelter Familie singen?',
  'Lieber 100€ jetzt oder 200€ in einem Monat?',
  'Lieber für eine Woche ins Weltall oder für ein Jahr auf eine Trauminsel?',
  'Lieber Hai oder Krokodil als Haustier?',
  'Lieber laute Musik im Auto oder Stille?',
  'Lieber Burger oder Döner?',
  'Lieber Cocktail oder Bier?',
  'Lieber Tatort oder Netflix-Serie?',
  'Lieber Karaoke oder Tanzfläche?',
  'Lieber Festival oder Cluburlaub?',
  'Lieber Roadtrip oder Pauschalreise?',
  'Lieber Apple oder Android?',
  'Lieber Mallorca oder Ibiza?',
  'Lieber Tor schießen oder Tor verhindern?',
  'Lieber Pizza Margherita oder Pizza Salami?',
  'Lieber Fußball gucken oder Fußball spielen?',
  'Lieber Fernseher oder Beamer?',
  'Lieber Klimaanlage oder Ventilator?',
  'Lieber Kerzenlicht oder Deckenleuchte?',
  'Lieber alleine wohnen oder WG?',
  'Lieber Marathon oder Sprint?',
  'Lieber Achterbahn oder Riesenrad?',
  'Lieber Skifahren oder Snowboard?',
  'Lieber Schach oder Poker?',
  'Lieber Tatort-Mörder kennen oder Filmende offen?',
  'Lieber Schokolade oder Gummibärchen?',
  'Lieber Cola oder Sprite?',
  'Lieber Kuchen oder Eis?',
  'Lieber Pasta selbst kochen oder bestellen?',
  'Lieber Pärchen-Urlaub oder Boyz-Trip?',
  'Lieber 30 Jahre älter aussehen oder 30 Jahre jünger denken?',
  'Lieber niemals lügen müssen oder niemals belogen werden?',
  'Lieber Superheld oder Superschurke sein?',
  'Lieber Batman oder Superman?',
  'Lieber Star Wars oder Herr der Ringe?',
  'Lieber Marvel oder DC?',
  'Lieber Late-Night-Snack oder Frühstücksbuffet?',
  'Lieber im Bett frühstücken oder am Tisch?',
  'Lieber 1 Wunsch frei oder 3 Wünsche mit der Bedingung dass dein Erzfeind 5 kriegt?',
  'Lieber Smartphone für immer weg oder Auto für immer weg?',
  'Lieber Wikipedia auswendig können oder jede Sprache der Welt sprechen?',
  'Lieber jeden Tag das gleiche Wetter oder jeden Tag was anderes?',
  'Lieber Joker oder Bane?',
  'Lieber Hogwarts oder Auenland?',
  'Lieber Zeitreise in Vergangenheit oder Zukunft?',
  'Lieber Held der Geschichte werden oder einfach in Ruhe leben?',
  'Lieber 10 Jahre länger leben oder 10 Jahre weniger Schlaf brauchen?',
  'Lieber 1 Tag Bundeskanzler sein oder 1 Tag Bundestrainer?',
  'Lieber im Sommer arbeiten und Winter frei oder andersrum?',
  'Lieber bei der Arbeit beleidigt werden oder beim Sport?',
  'Lieber 1 Mio € mit voller Steuer oder 500k € schwarz?',
  'Lieber WhatsApp-Verlauf öffentlich oder Browserverlauf öffentlich?',
  'Lieber kurz und intensiv oder lang und gemütlich?',
  'Lieber Spotify oder Apple Music?',
  'Lieber Sneaker oder Boots?',
  'Lieber Jeans oder Jogger?',
  'Lieber Bart oder rasiert?',
  'Lieber Brille oder Kontaktlinsen?',
  'Lieber Cap oder Beanie?',
  'Lieber Hoodie oder Sweater?',
  'Lieber Sommer-Festival in DE oder Winter-Trip in die Berge?',
  'Lieber Tinder-Date oder Blind-Date?',
  'Lieber Heiratsantrag im Restaurant oder unterwegs in der Natur?',
  'Lieber Hochzeit klein und intim oder groß und laut?',
  'Lieber Geschenk selbst gemacht oder gekauft?',
  'Lieber Mittagsschlaf oder Nachtschlaf länger?',
  'Lieber Wandern oder Fahrradfahren?',
  'Lieber Klettern oder Bouldern?',
  'Lieber Fitnessstudio oder Yoga?',
  'Lieber 5 km laufen oder 50 km Fahrrad?',
  'Lieber Sauna oder Eisbaden?',
  'Lieber Kreuzfahrt oder Wohnmobilurlaub?',
  'Lieber Stadt am Meer oder in den Bergen?',
  'Lieber Berlin oder München?',
  'Lieber Hamburg oder Köln?',
  'Lieber Schalke oder Dortmund?',
  'Lieber Bayern oder Gladbach?',
  'Lieber Fußball oder Handball?',
  'Lieber Basketball oder Volleyball?',
  'Lieber Tennis oder Padel?',
  'Lieber Boxen oder MMA?',
  'Lieber Talkshow oder Reality-TV?',
  'Lieber Tagesthemen oder TikTok für News?',
  'Lieber Podcast oder Hörbuch?',
  'Lieber Hörbuch oder lesen?',
  'Lieber Notizen auf Papier oder digital?',
  'Lieber Whiteboard oder Beamer in der Schule?',
  'Lieber Lehrer der nur lobt oder einer der dich pusht?',
  'Lieber spät kommen oder zu früh sein?',
  'Lieber morgens duschen oder abends duschen?',
  'Lieber Wanne oder Dusche?',
  'Lieber Kabel-Kopfhörer oder Bluetooth?',
  'Lieber Konzert in der ersten Reihe oder gemütlich hinten?',
  'Lieber Sitzplatz oder Stehplatz beim Fußball?',
  'Lieber kalter Winter mit Schnee oder milder Winter ohne Schnee?',
];
